
# Master Bedroom
#   Closet
- alias: 'Turn on master closet lights when door opens'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.ge_12722_onoff_relay_switch_switch_4

- alias: 'Turn off master closet lights when door closes'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.ge_12722_onoff_relay_switch_switch_4

# Foyer
- alias: 'Turn on downstairs lights when front door opens'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_2
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.downstairs

- alias: 'Turn on downstairs lights when garage door opens'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_3
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.downstairs

- alias: 'Turn off downstairs lights 5 min after front door closes'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_2
    to: 'off'
    for:
      minutes: 4
  action:
    service: homeassistant.turn_off
    entity_id: group.downstairs

- alias: 'Turn off downstairs lights 5 min after garage door closes'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_3
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: group.downstairs

# Aftons Bathroom
- alias: 'Turn on bathroom lights during the day'
  trigger:
    platform: state
    entity_id: old_entity_id: binary_sensor.ecolink_motion_detector_sensor_6_0
    to: 'on'
  condition:
    # When bath scene is not Closet
    # during the day
    - condition: state
      entity_id: scene.bath
      state: 'off'
    - condition: time
      after: '12:00:00'
      before: '22:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: scene.bright
- alias: 'Turn off bathroom lights when no motion'
  trigger:
    platform: state
    entity_id: old_entity_id: binary_sensor.ecolink_motion_detector_sensor_6_0
    to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: scene.bright
          state: 'on'
        - condition: state
          entity_id: scene.night
          state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id:
      - scene.bright
      - scene.night
- alias: 'Turn on bathroom lights at night'
  trigger:
    platform: state
    entity_id: old_entity_id: binary_sensor.ecolink_motion_detector_sensor_6_0
    to: 'on'
  condition:
    - condition: state
      entity_id: scene.bath
      state: 'off'
    - condition: time
      before: '12:00:00'
      after: '22:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: scene.night
- alias: 'Turn off bath scene'
  trigger:
    platform: state
    entity_id: scene.bath
    to: 'on'
    for:
      hours: 1
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: scene.bath
